name: Test Pipeline
 
on:
  push:
    branches: 
    - main
  workflow_dispatch:
 
env:
  DAY_OF_WEEK: Monday
 
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SELAMLAMA: Hello
    steps:
    - name: Checkout Adimi 
      uses: actions/checkout@v4
    - name: Osman Env Tanimlama
      run: |   
        echo "Hello World"
        echo $OSMAN
      env:
       OSMAN : "Bu Osman Bizim Osman bunu ad覺mda tan覺mlad覺m"
    - name: Bu da bir baska adim
      run: |
        echo $DAY_OF_WEEK
        echo $SELAMLAMA
        echo $OSMAN 
  test2:
    runs-on: ubuntu-latest
    steps:
     - name: ayr覺 jobdaki adim
       run: |
        echo $DAY_OF_WEEK
        echo $SELAMLAMA
        echo $OSMAN
