name: Test Pipeline

on:
    push:
        branches:
        - main
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Adimi
              uses: actions/checkout@v4
            - name: Osman Env Tanimlama
              run: |
                  echo "Hello World"
                  echo $OSMAN
              env: 
                  OSMAN: "Bu Osman Bizim Osman"
                    
