name: Test Pipeline

on:
    push:
        branches:
        - main
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Adimi
              uses: actions/check-out@v4
            - name: Environment Variable Listeleme
              run: printenv
                
